[workspace]
authors = ["Juan P. Fonseca-Zamora <69847296+juanfonsecaLS1@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "pre-processing"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
pandas = ">=3.0.0,<4"
shapely = ">=2.1.2,<3"
